[build]
  command = "pnpm run build"
  publish = "dist"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [[plugins.inputs.audits]]
    path = "index.html"

  [[plugins.inputs.audits]]
    path = "work.html"

  [[plugins.inputs.audits]]
    path = "writing.html"

  [[plugins.inputs.audits]]
    path = "contact.html"
